package Excepionstest;

public class TryCatchdemo {
	static ArithmeticException e;
	public static void main(String[] args) {
		throw e;
				
	}
}
